## find all RAxML_info files across the three dataset directories
## generated by Claude code w/ Andrew Hipp review

files_rax <- dir('data', recursive = TRUE, pattern = '_info\\.', full.names = TRUE)

## dataset directory names and their short labels used elsewhere in the pipeline
## empiricalRAD_denovo must come before empiricalRAD: the de_novo path also
## contains ref_RAxML_snps, so the first match wins via ds_hit[1]
datasets <- c(
    simRAD              = 'simulated_RAD',
    reSeq               = 'ReSeq_phylos',
    empiricalRAD_denovo = 'de_novo',
    empiricalRAD        = 'ref_RAxML_snps'
)

## extract the Alignment Patterns integer from one RAxML info file
parse_patterns <- function(f) {
    lines <- readLines(f, warn = FALSE)
    hit <- grep('^Alignment Patterns:', lines, value = TRUE)
    as.integer(sub('^Alignment Patterns:\\s+', '', hit[1]))
}

## build a per-file data frame with dataset label and pattern count
dat_patterns <- data.frame(
    file     = files_rax,
    dataset  = NA_character_,
    patterns = NA_integer_,
    stringsAsFactors = FALSE
)

for (i in seq_along(files_rax)) {
    ds_hit <- names(datasets)[sapply(datasets, grepl, x = files_rax[i], fixed = TRUE)]
    dat_patterns$dataset[i]  <- if (length(ds_hit)) ds_hit[1] else NA_character_
    dat_patterns$patterns[i] <- parse_patterns(files_rax[i])
}

## summarize: mean and SD of alignment patterns per dataset
out_patterns <- do.call(rbind, lapply(names(datasets), function(ds) {
    vals <- dat_patterns$patterns[dat_patterns$dataset == ds]
    data.frame(
        dataset       = ds,
        n             = length(vals),
        mean_sitePatterns = mean(vals, na.rm = TRUE) |> round(1),
        sd_sitePatterns   = sd(vals,   na.rm = TRUE) |> round(1)
    )
}))

if(globalDoPDF) write.csv(out_patterns, 'out/tables/raxml_site_patterns.csv', row.names = FALSE)
